### ISSUE TITLE
Incompatibility with Blender 3.3.6 and later

### ISSUE THREAD

**Issue by puchinekopuchiko** [nanoskript/vrm-rigify#7] opened 2023-08-09 09:36 UTC
After importing the VRM, only hair and part of faces can be animated after reparenting to the generated armature rig. This only happens after blender 3.3.6. This works well with no issue in blender 3.0.x with rigify version 0.6.4. 

This add-on is cool hidden gem, so would be nice if it can still be used with the newest blender version.

**Comment by nanoskript** [comment] 2023-08-19 11:19
Hi, thank you for opening an issue.

At the moment, I'm unable to reproduce this problem. I'm using Blender 3.6.2 with VRM Add-on for Blender 2.18.1. Do you have a VRM model file or Blender file that exhibits this issue?

**Comment by puchinekopuchiko** [comment] 2023-08-19 13:00
I'm just using the sample avatar from VRoid.  This is the blender file containing the issue.

More detail:
- Blender 3.6.2
- VRM 1.22.1 export VRM version 0.x
- VRM Add-on for Blender version 2.17.7

[Issue.zip](https://github.com/nanoskript/vrm-rigify/files/12385885/Issue.zip)

**Comment by nanoskript** [comment] 2023-08-20 02:35
Thank you! It looks like I hadn't updated the VRM Add-on for Blender extension correctly. I can reproduce the problem on their newer updates. I bisected their [list of releases](https://github.com/saturday06/VRM-Addon-for-Blender/releases), and it looks like the last working version was 2.15.26, and the first breaking version is 2.16.0.

The specific issue seems to be with the added geometry nodes in the meshes of the imported VRM model:

<img width="368" alt="image" src="https://github.com/nanoskript/vrm-rigify/assets/96655713/3d283f55-0f3a-4a87-8ab5-c16686278e3f">

I'll try to investigate a fix for this, but as an immediate workaround, these can be deleted or disabled and then posing works as normal.

**Comment by nanoskript** [comment] 2023-08-20 03:11
Added an additional installation step to the README in https://github.com/nanoskript/vrm-rigify/commit/c2eb56d44f0ec3883b68b0121a6da934ccba3a7d. Feel free to reopen this issue if you're still having problems.

**Closed by nanoskript** 2023-08-20 03:11 UTC
